import { IStats } from '../components/Stats/IStats';

export interface IKart {
  id: Karts;
  displayName: string;
  imageUrl: string;
  stats: IStats;
}

export function getKart(id: string): IKart {
  const kart = KARTS.find((kart) => kart.id === id);
  if (!kart) {
    throw new Error(`Kart associated with id ${id} not found.`);
  }
  return kart;
}

export enum Karts {
  StandardKart = 'standard-kart',
  PipeFrame = 'pipe-frame',
  Mach8 = 'mach-8',
  SteelDriver = 'steel-driver',
  CatCruiser = 'cat-cruiser',
  CircuitSpecial = 'circuit-special',
  TriSpeeder = 'tri-speeder',
  Badwagon = 'badwagon',
  Prancer = 'prancer',
  Biddybuggy = 'biddybuggy',
  Landship = 'landship',
  Sneeker = 'sneeker',
  SportsCoupe = 'sports-coupe',
  GoldStandard = 'gold-standard',
  StandardBike = 'standard-bike',
  Comet = 'comet',
  SportBike = 'sport-bike',
  TheDuke = 'the-duke',
  FlameRider = 'flame-rider',
  Varmint = 'varmint',
  MrScooty = 'mr-scooty',
  JetBike = 'jet-bike',
  YoshiBike = 'yoshi-bike',
  StandardAtv = 'standard-atv',
  WildWiggler = 'wild-wiggler',
  TeddyBuggy = 'teddy-buggy',
  Gla = 'gla',
  W25SilverArrow = 'w-25-silver-arrow',
  SlRoadster300 = '300-sl-roadster',
  BlueFalcon = 'blue-falcon',
  TanookiKart = 'tanooki-kart',
  BDasher = 'b-dasher',
  MasterCycle = 'master-cycle',
  Streetle = 'streetle',
  PWing = 'p-wing',
  CityTripper = 'city-tripper',
  BoneRattler = 'bone-rattler',
  KoopaClown = 'koopa-clown',
  SplatBuggy = 'splat-buggy',
  Inkstriker = 'inkstriker',
  MasterCycleZero = 'master-cycle-zero',
}

export const STANDARD_KART: IKart = {
  id: Karts.StandardKart,
  displayName: 'Standard Kart',
  imageUrl: 'https://mario.wiki.gallery/images/0/05/StandardKartBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 3,
    offRoadTraction: 3,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 3,
  },
};
export const PIPE_FRAME: IKart = {
  id: Karts.PipeFrame,
  displayName: 'Pipe Frame',
  imageUrl: 'https://mario.wiki.gallery/images/d/d1/PipeFrameBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 6,
    onRoadTraction: 3,
    offRoadTraction: 4,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 1,
    airSpeed: 1,
    groundHandling: 5,
    waterHandling: 4,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 3,
  },
};
export const MACH_8: IKart = {
  id: Karts.Mach8,
  displayName: 'Mach 8',
  imageUrl: 'https://mario.wiki.gallery/images/d/df/Mach8BodyMK8.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 2,
    offRoadTraction: 4,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 5,
    airSpeed: 4,
    groundHandling: 2,
    waterHandling: 2,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 3,
  },
};
export const STEEL_DRIVER: IKart = {
  id: Karts.SteelDriver,
  displayName: 'Steel Driver',
  imageUrl: 'https://www.mariowiki.com/images/9/94/Steel_Driver.png',
  stats: {
    weight: 4,
    acceleration: 1,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 3,
    groundSpeed: 4,
    waterSpeed: 5,
    antiGravitySpeed: 2,
    airSpeed: 0,
    groundHandling: 1,
    waterHandling: 5,
    antiGravityHandling: 1,
    airHandling: 1,
    invincibility: 6,
  },
};
export const CAT_CRUISER: IKart = {
  id: Karts.CatCruiser,
  displayName: 'Cat Cruiser',
  imageUrl: 'https://www.mariowiki.com/images/f/f4/CatCruiserBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 5,
    onRoadTraction: 4,
    offRoadTraction: 3,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 4,
    groundHandling: 4,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 3,
  },
};
export const CIRCUIT_SPECIAL: IKart = {
  id: Karts.CircuitSpecial,
  displayName: 'Circuit Special',
  imageUrl: 'https://www.mariowiki.com/images/6/6c/CircuitSpecialBodyMK8.png',
  stats: {
    weight: 3,
    acceleration: 1,
    onRoadTraction: 3,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 1,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 0,
    invincibility: 6,
  },
};
export const TRI_SPEEDER: IKart = {
  id: Karts.TriSpeeder,
  displayName: 'Tri-Speeder',
  imageUrl: 'https://www.mariowiki.com/images/5/56/TrispeederBodyMK8.png',
  stats: {
    weight: 4,
    acceleration: 1,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 3,
    groundSpeed: 4,
    waterSpeed: 5,
    antiGravitySpeed: 2,
    airSpeed: 0,
    groundHandling: 1,
    waterHandling: 5,
    antiGravityHandling: 1,
    airHandling: 1,
    invincibility: 6,
  },
};
export const BADWAGON: IKart = {
  id: Karts.Badwagon,
  displayName: 'Badwagon',
  imageUrl: 'https://www.mariowiki.com/images/c/c2/BadwagonBodyMK8.png',
  stats: {
    weight: 4,
    acceleration: 0,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 1,
    airHandling: 0,
    invincibility: 7,
  },
};
export const PRANCER: IKart = {
  id: Karts.Prancer,
  displayName: 'Prancer',
  imageUrl: 'https://www.mariowiki.com/images/f/ff/PrancerBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 2,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 5,
  },
};
export const BIDDYBUGGY: IKart = {
  id: Karts.Biddybuggy,
  displayName: 'Biddybuggy',
  imageUrl: 'https://www.mariowiki.com/images/4/45/BiddybuggyBodyMK8.png',
  stats: {
    weight: 0,
    acceleration: 7,
    onRoadTraction: 1,
    offRoadTraction: 4,
    miniTurbo: 7,
    groundSpeed: 0,
    waterSpeed: 1,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 5,
    waterHandling: 4,
    antiGravityHandling: 5,
    airHandling: 4,
    invincibility: 0,
  },
};
export const LANDSHIP: IKart = {
  id: Karts.Landship,
  displayName: 'Landship',
  imageUrl: 'https://www.mariowiki.com/images/6/6d/LandshipBodyMK8.png',
  stats: {
    weight: 0,
    acceleration: 6,
    onRoadTraction: 0,
    offRoadTraction: 6,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 5,
    antiGravitySpeed: 0,
    airSpeed: 2,
    groundHandling: 4,
    waterHandling: 5,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 2,
  },
};
export const SNEEKER: IKart = {
  id: Karts.Sneeker,
  displayName: 'Sneeker',
  imageUrl: 'https://www.mariowiki.com/images/4/47/SneakerBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 0,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 2,
    invincibility: 5,
  },
};
export const SPORTS_COUPE: IKart = {
  id: Karts.SportsCoupe,
  displayName: 'Sports Coupe',
  imageUrl: 'https://www.mariowiki.com/images/f/f8/SportsCoupeMK8.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 2,
    offRoadTraction: 4,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 5,
    airSpeed: 4,
    groundHandling: 2,
    waterHandling: 2,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 3,
  },
};
export const GOLD_STANDARD: IKart = {
  id: Karts.GoldStandard,
  displayName: 'Gold Standard',
  imageUrl: 'https://www.mariowiki.com/images/f/fe/Gold_Standard.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 0,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 2,
    invincibility: 4,
  },
};
export const STANDARD_BIKE: IKart = {
  id: Karts.StandardBike,
  displayName: 'Standard Bike',
  imageUrl: 'https://www.mariowiki.com/images/8/84/StandardBikeBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 5,
    onRoadTraction: 3,
    offRoadTraction: 5,
    miniTurbo: 5,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 3,
    invincibility: 4,
  },
};
export const COMET: IKart = {
  id: Karts.Comet,
  displayName: 'Comet',
  imageUrl: 'https://www.mariowiki.com/images/0/0e/CometBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 5,
    onRoadTraction: 4,
    offRoadTraction: 3,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 4,
    groundHandling: 4,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 2,
  },
};
export const SPORT_BIKE: IKart = {
  id: Karts.SportBike,
  displayName: 'Sport Bike',
  imageUrl: 'https://www.mariowiki.com/images/f/fe/SportBikeBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 2,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 3,
  },
};
export const THE_DUKE: IKart = {
  id: Karts.TheDuke,
  displayName: 'The Duke',
  imageUrl: 'https://www.mariowiki.com/images/8/8a/TheDukeBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 3,
    offRoadTraction: 3,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 3,
  },
};
export const FLAME_RIDER: IKart = {
  id: Karts.FlameRider,
  displayName: 'Flame Rider',
  imageUrl: 'https://www.mariowiki.com/images/3/31/FlameRiderBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 5,
    onRoadTraction: 3,
    offRoadTraction: 5,
    miniTurbo: 5,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 3,
    invincibility: 4,
  },
};
export const VARMINT: IKart = {
  id: Karts.Varmint,
  displayName: 'Varmint',
  imageUrl: 'https://www.mariowiki.com/images/d/d0/VarmintBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 6,
    onRoadTraction: 3,
    offRoadTraction: 4,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 1,
    airSpeed: 1,
    groundHandling: 5,
    waterHandling: 4,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 2,
  },
};
export const MR_SCOOTY: IKart = {
  id: Karts.MrScooty,
  displayName: 'Mr. Scooty',
  imageUrl: 'https://www.mariowiki.com/images/1/18/MrScootyBodyMK8.png',
  stats: {
    weight: 0,
    acceleration: 7,
    onRoadTraction: 1,
    offRoadTraction: 4,
    miniTurbo: 7,
    groundSpeed: 0,
    waterSpeed: 1,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 5,
    waterHandling: 4,
    antiGravityHandling: 5,
    airHandling: 4,
    invincibility: 0,
  },
};
export const JET_BIKE: IKart = {
  id: Karts.JetBike,
  displayName: 'Jet Bike',
  imageUrl: 'https://www.mariowiki.com/images/1/12/JetBikeBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 2,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 3,
  },
};
export const YOSHI_BIKE: IKart = {
  id: Karts.YoshiBike,
  displayName: 'Yoshi Bike',
  imageUrl: 'https://www.mariowiki.com/images/6/62/YoshiBikeBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 5,
    onRoadTraction: 4,
    offRoadTraction: 3,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 4,
    groundHandling: 4,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 2,
  },
};
export const STANDARD_ATV: IKart = {
  id: Karts.StandardAtv,
  displayName: 'Standard ATV',
  imageUrl: 'https://www.mariowiki.com/images/2/23/StandardATVBodyMK8.png',
  stats: {
    weight: 4,
    acceleration: 0,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 1,
    airHandling: 0,
    invincibility: 6,
  },
};
export const WILD_WIGGLER: IKart = {
  id: Karts.WildWiggler,
  displayName: 'Wild Wiggler',
  imageUrl: 'https://www.mariowiki.com/images/a/aa/WildWigglerBodyMK8.png',
  stats: {
    weight: 1,
    acceleration: 5,
    onRoadTraction: 3,
    offRoadTraction: 5,
    miniTurbo: 5,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 3,
    invincibility: 4,
  },
};
export const TEDDY_BUGGY: IKart = {
  id: Karts.TeddyBuggy,
  displayName: 'Teddy Buggy',
  imageUrl: 'https://www.mariowiki.com/images/f/fa/TeddyBuggyBodyMK8.png',
  stats: {
    weight: 2,
    acceleration: 5,
    onRoadTraction: 4,
    offRoadTraction: 3,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 4,
    groundHandling: 4,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 1,
  },
};
export const GLA: IKart = {
  id: Karts.Gla,
  displayName: 'GLA',
  imageUrl: 'https://www.mariowiki.com/images/c/c2/GLA-MK8.png',
  stats: {
    weight: 4,
    acceleration: 0,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 1,
    airHandling: 0,
    invincibility: 7,
  },
};
export const W_25_SILVER_ARROW: IKart = {
  id: Karts.W25SilverArrow,
  displayName: 'W 25 Silver Arrow',
  imageUrl: 'https://www.mariowiki.com/images/2/25/W25SilverArrow-MK8.png',
  stats: {
    weight: 1,
    acceleration: 5,
    onRoadTraction: 3,
    offRoadTraction: 5,
    miniTurbo: 5,
    groundSpeed: 2,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 3,
    invincibility: 4,
  },
};
export const SL_ROADSTER_300: IKart = {
  id: Karts.SlRoadster300,
  displayName: '300 SL Roadster',
  imageUrl: 'https://www.mariowiki.com/images/f/f4/300SLRoadster_MK8.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 3,
    offRoadTraction: 3,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 4,
  },
};
export const BLUE_FALCON: IKart = {
  id: Karts.BlueFalcon,
  displayName: 'Blue Falcon',
  imageUrl: 'https://www.mariowiki.com/images/f/f6/MK8BlueFalcon.png',
  stats: {
    weight: 0,
    acceleration: 3,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 2,
    waterHandling: 3,
    antiGravityHandling: 5,
    airHandling: 1,
    invincibility: 4,
  },
};
export const TANOOKI_KART: IKart = {
  id: Karts.TanookiKart,
  displayName: 'Tanooki Kart',
  imageUrl:
    'https://www.mariowiki.com/images/7/76/MK8_Tanooki_Buggy_Sprite.png',
  stats: {
    weight: 3,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 7,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 4,
  },
};
export const B_DASHER: IKart = {
  id: Karts.BDasher,
  displayName: '',
  imageUrl: 'https://www.mariowiki.com/images/1/15/ZeldaMK8Bdasher.png',
  stats: {
    weight: 3,
    acceleration: 1,
    onRoadTraction: 3,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 1,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 0,
    invincibility: 6,
  },
};
export const MASTER_CYCLE: IKart = {
  id: Karts.MasterCycle,
  displayName: 'Master Cycle',
  imageUrl: 'https://www.mariowiki.com/images/8/8a/MK8MasterCycle.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 1,
    offRoadTraction: 0,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 2,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 2,
    antiGravityHandling: 3,
    airHandling: 2,
    invincibility: 3,
  },
};
export const STREETLE: IKart = {
  id: Karts.Streetle,
  displayName: 'Streetle',
  imageUrl: 'https://www.mariowiki.com/images/c/cf/MK8Streetle.png',
  stats: {
    weight: 0,
    acceleration: 6,
    onRoadTraction: 0,
    offRoadTraction: 6,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 5,
    antiGravitySpeed: 0,
    airSpeed: 2,
    groundHandling: 4,
    waterHandling: 5,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 3,
  },
};
export const P_WING: IKart = {
  id: Karts.PWing,
  displayName: 'P-Wing',
  imageUrl: 'https://www.mariowiki.com/images/c/cd/MK8PWing.png',
  stats: {
    weight: 3,
    acceleration: 1,
    onRoadTraction: 3,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 5,
    waterSpeed: 1,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 0,
    invincibility: 6,
  },
};
export const CITY_TRIPPER: IKart = {
  id: Karts.CityTripper,
  displayName: 'City Tripper',
  imageUrl:
    'https://www.mariowiki.com/images/b/be/MK8_Light-Green_City_Tripper.png',
  stats: {
    weight: 1,
    acceleration: 6,
    onRoadTraction: 3,
    offRoadTraction: 4,
    miniTurbo: 6,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 1,
    airSpeed: 1,
    groundHandling: 5,
    waterHandling: 4,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 2,
  },
};
export const BONE_RATTLER: IKart = {
  id: Karts.BoneRattler,
  displayName: 'Bone Rattler',
  imageUrl: 'https://www.mariowiki.com/images/0/0a/MK8BoneRattler.png',
  stats: {
    weight: 4,
    acceleration: 1,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 3,
    groundSpeed: 4,
    waterSpeed: 5,
    antiGravitySpeed: 2,
    airSpeed: 0,
    groundHandling: 1,
    waterHandling: 5,
    antiGravityHandling: 1,
    airHandling: 1,
    invincibility: 5,
  },
};
export const KOOPA_CLOWN: IKart = {
  id: Karts.KoopaClown,
  displayName: 'Koopa Clown',
  imageUrl: 'https://www.mariowiki.com/images/7/70/MK8DX_Koopa_Clown.png',
  stats: {
    weight: 3,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 7,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 3,
  },
};
export const SPLAT_BUGGY: IKart = {
  id: Karts.SplatBuggy,
  displayName: 'Splat Buggy',
  imageUrl: 'https://www.mariowiki.com/images/6/63/MK8DX_Splat_Buggy.png',
  stats: {
    weight: 0,
    acceleration: 3,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 4,
    groundSpeed: 4,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 3,
    groundHandling: 2,
    waterHandling: 3,
    antiGravityHandling: 5,
    airHandling: 1,
    invincibility: 3,
  },
};
export const INKSTRIKER: IKart = {
  id: Karts.Inkstriker,
  displayName: 'Inkstriker',
  imageUrl: 'https://www.mariowiki.com/images/e/eb/MK8DX_Inkstriker.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 2,
    offRoadTraction: 4,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 3,
    antiGravitySpeed: 5,
    airSpeed: 4,
    groundHandling: 2,
    waterHandling: 2,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 1,
  },
};
export const MASTER_CYCLE_ZERO: IKart = {
  id: Karts.MasterCycleZero,
  displayName: 'Master Cycle Zero',
  imageUrl: 'https://www.mariowiki.com/images/2/26/MK8D_Master_Cycle_Zero.png',
  stats: {
    weight: 3,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 7,
    miniTurbo: 5,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 3,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 3,
  },
};

export const KARTS: IKart[] = [
  STANDARD_KART,
  PIPE_FRAME,
  MACH_8,
  STEEL_DRIVER,
  CAT_CRUISER,
  CIRCUIT_SPECIAL,
  TRI_SPEEDER,
  BADWAGON,
  PRANCER,
  BIDDYBUGGY,
  LANDSHIP,
  SNEEKER,
  SPORTS_COUPE,
  GOLD_STANDARD,
  STANDARD_BIKE,
  COMET,
  SPORT_BIKE,
  THE_DUKE,
  FLAME_RIDER,
  VARMINT,
  MR_SCOOTY,
  JET_BIKE,
  YOSHI_BIKE,
  STANDARD_ATV,
  WILD_WIGGLER,
  TEDDY_BUGGY,
  GLA,
  W_25_SILVER_ARROW,
  SL_ROADSTER_300,
  BLUE_FALCON,
  TANOOKI_KART,
  B_DASHER,
  MASTER_CYCLE,
  STREETLE,
  P_WING,
  CITY_TRIPPER,
  BONE_RATTLER,
  KOOPA_CLOWN,
  SPLAT_BUGGY,
  INKSTRIKER,
  MASTER_CYCLE_ZERO,
];
