import { IStats } from '../components/Stats/IStats';

export interface ITire {
  id: Tires;
  displayName: string;
  imageUrl: string;
  stats: IStats;
}

export function getTire(id: string) {
  const tire = TIRES.find((tire) => tire.id === id);
  if (!tire) {
    throw new Error(`Tire associated with id ${id} not found.`);
  }
  return tire;
}

export enum Tires {
  Standard = 'standard-tire',
  Monster = 'monster-tire',
  Roller = 'roller-tire',
  SlimTire = 'slim-tire',
  Slick = 'slick-tire',
  Metal = 'metal-tire',
  Button = 'button-tire',
  OffRoad = 'off-road-tire',
  Sponge = 'sponge-tire',
  Wood = 'wood-tire',
  Cushion = 'cushion-tire',
  BlueStandard = 'blue-standard-tire',
  HotMonster = 'hot-monster-tire',
  AzureRoller = 'azure-roller-tire',
  CrimsonSlim = 'crimson-slim-tire',
  CyberSlick = 'cyber-slick-tire',
  RetroOffRoad = 'retro-off-road-tire',
  GoldTires = 'gold-tires',
  GlaTires = 'gla-tires',
  TriforceTires = 'triforce-tires',
  LeafTires = 'leaf-tires',
  AncientTires = 'ancient-tires',
}

export const STANDARD_TIRE: ITire = {
  id: Tires.Standard,
  displayName: 'Standard',
  imageUrl: 'https://mario.wiki.gallery/images/a/a8/StandardTiresMK8.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 4,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 2,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 4,
  },
};
export const MONSTER_TIRE: ITire = {
  id: Tires.Monster,
  displayName: 'Monster',
  imageUrl: 'https://mario.wiki.gallery/images/2/29/MonsterTiresMK8.png',
  stats: {
    weight: 4,
    acceleration: 2,
    onRoadTraction: 3,
    offRoadTraction: 7,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 0,
    airHandling: 1,
    invincibility: 6,
  },
};
export const ROLLER_TIRE: ITire = {
  id: Tires.Roller,
  displayName: 'Roller',
  imageUrl: 'https://mario.wiki.gallery/images/7/76/RollerTiresMK8.png',
  stats: {
    weight: 0,
    acceleration: 6,
    onRoadTraction: 0,
    offRoadTraction: 4,
    miniTurbo: 6,
    groundSpeed: 0,
    waterSpeed: 3,
    antiGravitySpeed: 0,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 4,
    airHandling: 4,
    invincibility: 0,
  },
};
export const SLIM_TIRE: ITire = {
  id: Tires.SlimTire,
  displayName: 'Slim',
  imageUrl: 'https://www.mariowiki.com/images/f/f8/SlimTiresMK8.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 5,
  },
};
export const SLICK_TIRE: ITire = {
  id: Tires.Slick,
  displayName: 'Slick',
  imageUrl: 'https://www.mariowiki.com/images/d/dd/SlickTiresMK8.png',
  stats: {
    weight: 3,
    acceleration: 1,
    onRoadTraction: 4,
    offRoadTraction: 0,
    miniTurbo: 2,
    groundSpeed: 4,
    waterSpeed: 0,
    antiGravitySpeed: 4,
    airSpeed: 0,
    groundHandling: 2,
    waterHandling: 0,
    antiGravityHandling: 2,
    airHandling: 1,
    invincibility: 5,
  },
};
export const METAL_TIRE: ITire = {
  id: Tires.Metal,
  displayName: 'Metal',
  imageUrl: 'https://www.mariowiki.com/images/9/96/MetalTiresMK8.png',
  stats: {
    weight: 4,
    acceleration: 0,
    onRoadTraction: 1,
    offRoadTraction: 2,
    miniTurbo: 2,
    groundSpeed: 4,
    waterSpeed: 3,
    antiGravitySpeed: 1,
    airSpeed: 2,
    groundHandling: 2,
    waterHandling: 2,
    antiGravityHandling: 1,
    airHandling: 0,
    invincibility: 6,
  },
};
export const BUTTON_TIRE: ITire = {
  id: Tires.Button,
  displayName: 'Button',
  imageUrl: 'https://www.mariowiki.com/images/0/07/ButtonTiresMK8.png',
  stats: {
    weight: 0,
    acceleration: 5,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 5,
    groundSpeed: 1,
    waterSpeed: 2,
    antiGravitySpeed: 2,
    airSpeed: 2,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 3,
  },
};
export const OFF_ROAD_TIRE: ITire = {
  id: Tires.OffRoad,
  displayName: 'Off-Road',
  imageUrl: 'https://www.mariowiki.com/images/2/25/Off-Road.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 3,
    offRoadTraction: 6,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 2,
    invincibility: 6,
  },
};
export const SPONGE_TIRE: ITire = {
  id: Tires.Sponge,
  displayName: 'Sponge',
  imageUrl: 'https://www.mariowiki.com/images/4/4c/SpongeTiresMK8.png',
  stats: {
    weight: 1,
    acceleration: 4,
    onRoadTraction: 2,
    offRoadTraction: 6,
    miniTurbo: 5,
    groundSpeed: 1,
    waterSpeed: 1,
    antiGravitySpeed: 1,
    airSpeed: 4,
    groundHandling: 2,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 4,
  },
};
export const WOOD_TIRE: ITire = {
  id: Tires.Wood,
  displayName: 'Wood',
  imageUrl: 'https://www.mariowiki.com/images/0/03/WoodTiresMK8.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 5,
  },
};
export const CUSHION_TIRE: ITire = {
  id: Tires.Cushion,
  displayName: 'Cushion',
  imageUrl: 'https://www.mariowiki.com/images/9/92/CushionTiresMK8.png',
  stats: {
    weight: 1,
    acceleration: 4,
    onRoadTraction: 2,
    offRoadTraction: 6,
    miniTurbo: 5,
    groundSpeed: 1,
    waterSpeed: 1,
    antiGravitySpeed: 1,
    airSpeed: 4,
    groundHandling: 2,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 3,
    invincibility: 6,
  },
};
export const BLUE_STANDARD_TIRE: ITire = {
  id: Tires.BlueStandard,
  displayName: 'Blue Standard',
  imageUrl: 'https://www.mariowiki.com/images/d/db/Blue_Standard.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 4,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 2,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 4,
  },
};
export const HOT_MONSTER_TIRE: ITire = {
  id: Tires.HotMonster,
  displayName: 'Hot Monster',
  imageUrl: 'https://www.mariowiki.com/images/d/d1/HotMonsterTiresMK8.png',
  stats: {
    weight: 4,
    acceleration: 2,
    onRoadTraction: 3,
    offRoadTraction: 7,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 0,
    airHandling: 1,
    invincibility: 6,
  },
};
export const AZURE_ROLLER_TIRE: ITire = {
  id: Tires.AzureRoller,
  displayName: 'Azure Roller',
  imageUrl: 'https://www.mariowiki.com/images/f/fe/AzureRollerTiresMK8.png',
  stats: {
    weight: 0,
    acceleration: 6,
    onRoadTraction: 0,
    offRoadTraction: 4,
    miniTurbo: 6,
    groundSpeed: 0,
    waterSpeed: 3,
    antiGravitySpeed: 0,
    airSpeed: 3,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 4,
    airHandling: 4,
    invincibility: 0,
  },
};
export const CRIMSON_SLIM_TIRE: ITire = {
  id: Tires.CrimsonSlim,
  displayName: 'Crimson Slim',
  imageUrl: 'https://www.mariowiki.com/images/7/71/CrimsonSlimTiresMK8.png',
  stats: {
    weight: 2,
    acceleration: 2,
    onRoadTraction: 4,
    offRoadTraction: 1,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 4,
    airSpeed: 2,
    groundHandling: 4,
    waterHandling: 4,
    antiGravityHandling: 3,
    airHandling: 4,
    invincibility: 5,
  },
};
export const CYBER_SLICK_TIRE: ITire = {
  id: Tires.CyberSlick,
  displayName: 'Cyber Slick',
  imageUrl: 'https://www.mariowiki.com/images/2/29/CyberSlickTiresMK8.png',
  stats: {
    weight: 3,
    acceleration: 1,
    onRoadTraction: 4,
    offRoadTraction: 0,
    miniTurbo: 2,
    groundSpeed: 4,
    waterSpeed: 0,
    antiGravitySpeed: 4,
    airSpeed: 0,
    groundHandling: 2,
    waterHandling: 0,
    antiGravityHandling: 2,
    airHandling: 1,
    invincibility: 5,
  },
};
export const RETRO_OFF_ROAD_TIRE: ITire = {
  id: Tires.RetroOffRoad,
  displayName: 'Retro Off-Road',
  imageUrl: 'https://www.mariowiki.com/images/4/48/Retro_Off-Road.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 3,
    offRoadTraction: 6,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 2,
    invincibility: 6,
  },
};
export const GOLD_TIRES: ITire = {
  id: Tires.GoldTires,
  displayName: 'Gold Tires',
  imageUrl: 'https://www.mariowiki.com/images/5/52/Gold_Tires_MK8.png',
  stats: {
    weight: 4,
    acceleration: 0,
    onRoadTraction: 1,
    offRoadTraction: 2,
    miniTurbo: 2,
    groundSpeed: 4,
    waterSpeed: 3,
    antiGravitySpeed: 1,
    airSpeed: 2,
    groundHandling: 2,
    waterHandling: 2,
    antiGravityHandling: 1,
    airHandling: 0,
    invincibility: 5,
  },
};
export const GLA_TIRES: ITire = {
  id: Tires.GlaTires,
  displayName: 'GLA Tires',
  imageUrl: 'https://www.mariowiki.com/images/b/ba/GLATires-MK8.png',
  stats: {
    weight: 2,
    acceleration: 4,
    onRoadTraction: 2,
    offRoadTraction: 5,
    miniTurbo: 4,
    groundSpeed: 2,
    waterSpeed: 3,
    antiGravitySpeed: 2,
    airSpeed: 3,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 3,
    airHandling: 3,
    invincibility: 5,
  },
};
export const TRIFORCE_TIRES: ITire = {
  id: Tires.TriforceTires,
  displayName: 'Triforce Tires',
  imageUrl: 'https://www.mariowiki.com/images/9/9d/MK8-TriforceTires.png',
  stats: {
    weight: 3,
    acceleration: 3,
    onRoadTraction: 3,
    offRoadTraction: 6,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 4,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 1,
    waterHandling: 1,
    antiGravityHandling: 2,
    airHandling: 2,
    invincibility: 5,
  },
};
export const LEAF_TIRES: ITire = {
  id: Tires.LeafTires,
  displayName: 'Leaf Tires',
  imageUrl: 'https://www.mariowiki.com/images/f/f9/Leaf_Tires_MK8.png',

  stats: {
    weight: 0,
    acceleration: 5,
    onRoadTraction: 1,
    offRoadTraction: 3,
    miniTurbo: 5,
    groundSpeed: 1,
    waterSpeed: 2,
    antiGravitySpeed: 2,
    airSpeed: 2,
    groundHandling: 3,
    waterHandling: 3,
    antiGravityHandling: 4,
    airHandling: 2,
    invincibility: 3,
  },
};
export const ANCIENT_TIRES: ITire = {
  id: Tires.AncientTires,
  displayName: 'Ancient Tires',
  imageUrl: 'https://www.mariowiki.com/images/d/d5/MK8D_Ancient_Tires.png',
  stats: {
    weight: 4,
    acceleration: 2,
    onRoadTraction: 3,
    offRoadTraction: 7,
    miniTurbo: 3,
    groundSpeed: 3,
    waterSpeed: 2,
    antiGravitySpeed: 2,
    airSpeed: 1,
    groundHandling: 0,
    waterHandling: 1,
    antiGravityHandling: 0,
    airHandling: 1,
    invincibility: 5,
  },
};

export const TIRES: ITire[] = [
  STANDARD_TIRE,
  MONSTER_TIRE,
  ROLLER_TIRE,
  SLIM_TIRE,
  SLICK_TIRE,
  METAL_TIRE,
  BUTTON_TIRE,
  OFF_ROAD_TIRE,
  SPONGE_TIRE,
  WOOD_TIRE,
  CUSHION_TIRE,
  BLUE_STANDARD_TIRE,
  HOT_MONSTER_TIRE,
  AZURE_ROLLER_TIRE,
  CRIMSON_SLIM_TIRE,
  CYBER_SLICK_TIRE,
  RETRO_OFF_ROAD_TIRE,
  GOLD_TIRES,
  GLA_TIRES,
  TRIFORCE_TIRES,
  LEAF_TIRES,
  ANCIENT_TIRES,
];
